version: '3'

services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
  nlm_ingestor:
    image: ghcr.io/nlmatics/nlm-ingestor:latest
    depends_on:
      - neo4j
    ports:
      - "5001:5001"
      - "5002:5002"
  h2o_wave_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nlm_ingestor
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    ports:
      - "10101:10101"
    volumes:
      - .:/app
